version: "3.8"

services:
  rabbitmq:
    image: rabbitmq:3-management # Image có giao diện quản lý web
    ports:
      - "5672:5672" # Cổng kết nối từ code (AMQP)
      - "15672:15672" # Cổng web UI (http://localhost:15672)
    environment:
      RABBITMQ_DEFAULT_USER: admin # Username đăng nhập
      RABBITMQ_DEFAULT_PASS: admin # Password đăng nhập

  redis:
    image: redis:latest
    container_name: btncnnt_redis
    ports:
      - "6379:6379"
    restart: unless-stopped
    # Neu du an dung network rieng thi uncomment dong duoi
    # networks:
    #   - app-network
